"""empty message

Revision ID: 3bbcdff480f4
Revises: 82fcdb5d93d5
Create Date: 2023-05-31 13:04:05.338113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bbcdff480f4'
down_revision = '82fcdb5d93d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('Long')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Long', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
