version: "3.10"
services:
  pokemon_api: 
    image: python-docker:latest
    container_name: Pokemon-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 

    environment:
      DATABASE_URI: postgresql+psycopg2://pok:pok@db/pokk  

    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: pok
      POSTGRES_PASSWORD: pok
      POSTGRES_DB: pokk
    ports:
      - "5432:5432"
