"""empty message

Revision ID: 08ff8fc52735
Revises: 9e0a6dbbd07f
Create Date: 2023-06-06 15:04:38.980002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ff8fc52735'
down_revision = '9e0a6dbbd07f'
branch_labels = None
depends_on = None

def upgrade():
    with op.get_context().autocommit_block():
        op.execute("ALTER TABLE pokemon ALTER COLUMN legendary TYPE BOOLEAN USING legendary::boolean")



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('legendary',
               existing_type=sa.TEXT(),
               type_=sa.Boolean(),
               existing_nullable=True)

    ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('legendary',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
