"""empty message

Revision ID: fa79fe0a0d55
Revises: 
Create Date: 2023-06-06 12:56:47.529710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa79fe0a0d55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sp_atk', sa.Integer(), nullable=True))
        batch_op.drop_column('sp_atk_1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sp_atk_1', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('sp_atk')

    # ### end Alembic commands ###
